name: Marcar asistencia en Moodle

on:
  schedule:
    - cron: '1 19 * * 1,3' 
jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: pip install selenium webdriver-manager schedule

      - name: Ejecutar el script de asistencia
        run: python main.py 
