name: Marcar asistencia en Moodle

on:
  schedule:
    - cron: '1 19 * * 1,3' # Ejecutar los lunes y miércoles a las 19:01 UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Instalar Chrome y ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt-get install -y ./google-chrome-stable_current_amd64.deb
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          wget https://chromedriver.storage.googleapis.com/$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          chromedriver --version

      - name: Instalar dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pytest

      - name: Ejecutar script de asistencia
        run: python main.py
